/**
 * Auto-Reorder Service — Checks for low stock and creates draft POs
 */
const prisma = require('../config/prisma');
const logger = require('../utils/logger');

async function checkAndCreateReorders() {
    try {
        // Fetch active items and compute low stock using JS comparison.
        const allItems = await prisma.inventory.findMany({
            where: { isActive: true },
            include: { office: { select: { id: true, name: true } } },
        });

        const needReorder = allItems.filter(item => item.currentQuantity <= item.reorderPoint);

        if (needReorder.length === 0) {
            logger.info('[AutoReorder] No items need reordering');
            return [];
        }

        logger.info(`[AutoReorder] ${needReorder.length} items below reorder point`);

        // Group by vendor + office for batch PO creation
        const groups = {};
        for (const item of needReorder) {
            const vendorKey = item.primaryVendorId || 'NO_VENDOR';
            const key = `${vendorKey}_${item.officeId}`;
            if (!groups[key]) {
                groups[key] = { vendorId: item.primaryVendorId, officeId: item.officeId, items: [] };
            }
            groups[key].items.push(item);
        }

        const createdPOs = [];

        for (const [key, group] of Object.entries(groups)) {
            if (!group.vendorId) {
                logger.warn(`[AutoReorder] ${group.items.length} items have no vendor, skipping`);
                continue;
            }

            // Check if there's already a draft PO for this vendor+office
            const existingDraft = await prisma.purchaseOrder.findFirst({
                where: {
                    vendorId: group.vendorId,
                    officeId: group.officeId,
                    status: 'DRAFT',
                },
            });

            if (existingDraft) {
                logger.info(`[AutoReorder] Draft PO ${existingDraft.poNumber} already exists for vendor ${group.vendorId}, skipping`);
                continue;
            }

            // Generate PO number
            const counter = await prisma.counter.upsert({
                where: { name: 'po_number' },
                update: { sequence: { increment: 1 } },
                create: { name: 'po_number', prefix: 'PO', sequence: 1 },
            });
            const poNumber = `AR-${String(counter.sequence).padStart(6, '0')}`;

            // Find a manager as requestor
            const manager = await prisma.user.findFirst({
                where: {
                    officeId: group.officeId,
                    role: { in: ['MANAGER', 'ADMIN', 'SUPER_ADMIN'] },
                    isActive: true,
                },
                select: { id: true },
            });

            if (!manager) {
                logger.warn(`[AutoReorder] No manager found for office ${group.officeId}, skipping`);
                continue;
            }

            // Calculate totals
            const items = group.items.map(item => ({
                inventoryId: item.id,
                name: item.name,
                description: `Auto-reorder: Stock at ${item.currentQuantity}/${item.reorderPoint}`,
                quantity: item.reorderQuantity,
                unitPrice: item.lastPurchasePrice || item.unitCost || item.costPrice || 0,
                totalPrice: (item.reorderQuantity) * (item.lastPurchasePrice || item.unitCost || item.costPrice || 0),
            }));

            const subtotal = items.reduce((sum, i) => sum + (i.totalPrice || 0), 0);

            const po = await prisma.purchaseOrder.create({
                data: {
                    poNumber,
                    vendorId: group.vendorId,
                    officeId: group.officeId,
                    requestedById: manager.id,
                    status: 'DRAFT',
                    subtotal,
                    totalAmount: subtotal,
                    notes: 'Auto-generated by low stock alert',
                    items: { create: items },
                },
            });

            // Notify manager
            await prisma.notification.create({
                data: {
                    recipientId: manager.id,
                    type: 'LOW_STOCK',
                    title: '📦 Auto-Reorder PO Created',
                    message: `Draft PO ${poNumber} created for ${items.length} low-stock items. Please review and approve.`,
                    priority: 'HIGH',
                    relatedModel: 'PurchaseOrder',
                    relatedDocId: po.id,
                },
            });

            createdPOs.push(poNumber);
            logger.info(`[AutoReorder] Created draft PO ${poNumber} with ${items.length} items`);
        }

        return createdPOs;
    } catch (err) {
        logger.error('[AutoReorder] Failed:', err);
        return [];
    }
}

module.exports = { checkAndCreateReorders };
